options:
  formatter: stylish
files:
  include: '**/*.s(a|c)ss'
  ignore: 'node_modules/**'
rules:
  # 0 => turn off
  # 1 => warning  需要要命令上添加 --verobse 才行
  # 2 => error    此情况化看不到错误的详情，只会出一个 Error，所以没必要使用

  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 0
  empty-line-between-blocks: 1
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 0
  hex-notation: 0
  indentation: 1
  leading-zero: 1
  nesting-depth: 1
  # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml
  property-sort-order:
    - 1
    -
      order:
        # Box
        - 'display'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'order'

        - 'width'
        - 'min-width'
        - 'max-width'

        - 'height'
        - 'min-height'
        - 'max-height'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'float'
        - 'clear'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'transform'
        - 'transition'

        # Border

        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'outline'
        - 'outline-color'
        - 'outline-offset'
        - 'outline-style'
        - 'outline-width'

        # Background

        - 'background'
        - 'background-clip'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'

        # Text

        - 'color'

        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-smoothing'
        - 'font-style'
        - 'font-variant'
        - 'font-weight'

        - 'letter-spacing'
        - 'line-height'
        - 'list-style'

        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-transform'
        - 'text-wrap'

        - 'white-space'
        - 'word-spacing'

        # Other

        - 'border-collapse'
        - 'border-spacing'
        - 'box-shadow'
        - 'caption-side'
        - 'content'
        - 'cursor'
        - 'empty-cells'
        - 'opacity'
        - 'overflow'
        - 'quotes'
        - 'speak'
        - 'table-layout'
        - 'vertical-align'
        - 'visibility'
        - 'z-index'

  quotes:
    - 1
    -
      style: dobule
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 0
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
